In [11]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [12]:
exponents = np.arange(1,21)
bases = np.ones(20) * 2

# we can also use the exponents as the denominators

answer = np.power(bases, exponents) / exponents
answer

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [13]:
array1 = np.power(np.ones(6) / 10, np.arange(0,16,3))

array2 = np.power(np.ones(6) / 5, np.arange(0,21,4))

answer = np.dot(array1, array2)
answer

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [14]:
np.indices([8,8]).sum(axis=0) % 2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [15]:
X = np.random.random((5, 2))
print("Cartesian",'\n', X)

radius = np.sqrt(np.power(X[:,0], 2) + np.power(X[:,1], 2))
tetta = np.arctan2(X[:,1], X[:,0])

newX = np.ones((5,2))
newX[:,0] = radius
newX[:,1] = tetta
print("Polar", '\n', newX)

Cartesian 
 [[0.3965425  0.69353458]
 [0.65251151 0.93681504]
 [0.22549297 0.57288402]
 [0.58673735 0.30418405]
 [0.929793   0.55940983]]
Polar 
 [[0.79889684 1.05139262]
 [1.14166269 0.96240896]
 [0.61566483 1.19581054]
 [0.66089988 0.4782851 ]
 [1.0851057  0.54163175]]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [16]:
X = np.random.random((10, 10))

max_index = np.argmax(X)

row_index = max_index // 10
colon_index = max_index % 10

print('position: ', (row_index, colon_index))

print('value: ', X[row_index, colon_index])

position:  (2, 3)
value:  0.9970040417364692


**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [17]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

distances = np.sqrt(np.power((X[:,0]-y[0,0]), 2) + np.power((X[:,1]-y[0,1]), 2))
min_distance = np.min(distances)
index = np.where(distances == min_distance)

print(X[index,:])

[[[0.52885759 0.12926843]]]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [18]:
def f(x):
    if x < 0:
        return x ** 2 + 2 * x + 6
    elif x >= 2:
        return x ** 2 + 4 * x - 4
    else:
        return x + 6


x_axis = np.linspace(-3, 3, 100)
f_vectorized = np.vectorize(f)
y_axis = f_vectorized(x_axis)
print(y_axis)

[ 9.          8.76124885  8.52984389  8.30578512  8.08907254  7.87970615
  7.67768595  7.48301194  7.29568411  7.11570248  6.94306703  6.77777778
  6.61983471  6.46923783  6.32598714  6.19008264  6.06152433  5.94031221
  5.82644628  5.71992654  5.62075298  5.52892562  5.44444444  5.36730946
  5.29752066  5.23507805  5.17998163  5.1322314   5.09182736  5.05876951
  5.03305785  5.01469238  5.00367309  5.          5.00367309  5.01469238
  5.03305785  5.05876951  5.09182736  5.1322314   5.17998163  5.23507805
  5.29752066  5.36730946  5.44444444  5.52892562  5.62075298  5.71992654
  5.82644628  5.94031221  6.03030303  6.09090909  6.15151515  6.21212121
  6.27272727  6.33333333  6.39393939  6.45454545  6.51515152  6.57575758
  6.63636364  6.6969697   6.75757576  6.81818182  6.87878788  6.93939394
  7.          7.06060606  7.12121212  7.18181818  7.24242424  7.3030303
  7.36363636  7.42424242  7.48484848  7.54545455  7.60606061  7.66666667
  7.72727273  7.78787879  7.84848485  7.90909091  7.

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [19]:
X = np.random.random((10, 10))
Y = X - X.mean(axis=0, keepdims=True)

# check the result
print(Y.mean(axis=0, keepdims=True))

[[-2.22044605e-17 -4.44089210e-17  1.11022302e-17 -1.11022302e-17
   2.22044605e-17  1.11022302e-17 -8.88178420e-17 -2.22044605e-17
   3.33066907e-17 -2.77555756e-17]]


**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [20]:
X = np.random.normal(loc=5, scale=2., size=1000)
indices = np.random.randint(0,1000, size = 300)

expected_value = np.mean(X[indices])
print('expected_value ',expected_value)

variance = np.mean(np.power(X[indices] - expected_value,2))
print('variance', variance)

expected_value  5.196727144413953
variance 3.766101866072098


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [21]:
np.indices([5,5]).sum(axis=0) % 5

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [22]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 4, 0, 4, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [23]:
def sample2(x, c):
    assert len(x) > 0
    
    indices = np.arange(0, len(x))
    probability = x / np.sum(x)
    return np.random.choice(indices, size=c, p=probability)

            
sample2([50, 3, 1, 7, 20], 5)  
    

array([0, 0, 4, 4, 0])